src/Controller/Security/LoginController.php
Removed the showing of the caught error message in LoginController.
Instead it now shows a default "Invalid credentials." message.
As a result the interface will never show if the given email
is known in the database.
=> Fixed revealing login error

.github/workflows/testing.yml, README.md, composer.json, phpunit.xml.dist, sonar-project.properties
This commit integrates SonarCloud into the repository. It adds badges
to README.md, indicating the current health of the project. Moreover,
phpunit is integrated with SonarCloud through the newly added
sonar-project.properties. Composer.json and phpunit.xml.dist had to be
updated accordingly. Lastly, the testing workflow has actively
integrated a SonarCloud report.
=> Integrate SonarCloud into the workflow

.gitpod.Dockerfile
This commit adds the xdebug extension to the gitpod dockerfile. Since
the requirement has been added in the composer.json by 9e6b21e, the
gitpod has been broken. This change intends to fix that.
=> Install PHP extensions in the gitpod dockerfile

templates/activity/show.html.twig
Problem: Impossible to add enter spaces to a description for an activity. now possible.
Solved with recommended method by adding nl2br to a specific line in show.html.twig template.
=> First commit, Fixed Bug #150

assets/style/components/main/_nav.scss
A regression broke the top bar spacing in the main UI. This commit fixes
that.
=> Revert top bar spacing behaviour

assets/style/components/_table.scss
Previously, table heads were hidden on mobile. This was because big
tables might contain a long list of columns. However, in practice, this
seems to not be a big problem. Therefore, this commit changes that.
=> Show table heads on mobile

src/Form/Activity/Admin/ActivityEditType.php
Previously, a placeholder value was implemented in the activity forms for the
capacity field. However, this was done by overriding the data attribute in the
form, which modifies the actual data when an activity is editted. This is
unintended and can be easily overlooked by a user. This hotfix changes the
data attribute to the "attr" attribute, which directly integrates it into the
placeholder html attribute.
=> Hotfix for data override in Activity forms

.github/workflows/testing.yml, composer.json, composer.lock, phpstan-baseline.neon, phpstan.neon.dist, src/Command/HasLocalAccountCommand.php, src/Controller/Admin/AdminController.php, src/Controller/Admin/EventController.php, src/Controller/Admin/GroupController.php, src/Controller/Admin/MailController.php, src/Controller/Organise/OrganiseController.php, src/Form/Activity/ActivityCountPresent.php, src/Form/Activity/PriceOptionType.php, src/Form/Group/GroupType.php, src/Form/Group/RelationAddType.php, src/Form/Security/LocalAccountType.php, src/Form/Security/NewPasswordType.php, src/Form/Security/PasswordRequestType.php, src/Security/LocalAuthenticator.php, src/Template/AnnotationMenuExtension.php, src/Tests/Database/Activity/PriceOptionFixture.php, src/Tests/Database/Activity/RegistrationFixture.php, src/Tests/Database/Group/GroupFixture.php, src/Tests/Database/Mail/MailFixture.php, symfony.lock, tests/Integration/Form/Activity/PriceOptionTypeTest.php
This PR adds the PhpStan static analyser to kiwi. The intention is to further improve the quality and maintainability of the codebase, by adding more automated checks to pull requests. However, this might further strain the development speed of the project. PhpStan was chosen given the fact that it's the most actively used static code analyser for PHP.
The PR integrates a number of additional phpstan extensions for Symfony, Doctrine and PHPUnit, and provides a configuration file for PhpStan which tests both source code and tests on the maximum analysis level. It has parallel processing enabled for performance and integrates with the phpunit bridge by Symfony, which provides phpunit outside of the vendor folder. A baseline has been added, which will allow for the gradual fixing of errors. …
=> Static code analysis

.github/workflows/db.yml, src/Entity/Activity/Activity.php
This PR adds a new github actions pipeline. The pipeline is intended to check whether the migrations are matching the entity definitions. It accomplishes this by running all migrations, after which it tries to create a new migration automatically. If this fails, that means that no changes are available, as intended. It then tries to load the fixtures used in testing, which it uses during testing of the down migration, in order to check that the down migrations function properly as well. Given the fact that an actual MySql database is necessary to execute the migrations, the choice has been made to create a new pipeline, instead of integrating it into an existing pipeline.
=> Database testing pipeline

tests/Functional/Command/CreateLocalAccountCommandTest.php
The test is now skipped if on a windows.
=> Fixed the WIN only test error.

templates/admin/activity/show.html.twig, templates/admin/group/show.html.twig, templates/admin/security/show.html.twig, templates/organise/activity/show.html.twig, templates/organise/index.html.twig
This PR adds a number of buttons for admins & organisers, which allows them to send e-mails to participants for activities. A button is added for anyone individually who has registered, deregistered or is on the reserve list.
Additionally, a button is added to send a mail to all registered participants, which respects the registrants privacy by using the BCC field. The system works by utilizing the "mailto:" URL construct.
=> Send e-mails to participants

templates/admin/activity/show.html.twig
This PR updates the activity overview page, specifically the registrants. All actions have been moved to the correct column and "Mailen" is always the first option, adding consistency to the UI.
=> Constistent registrant actions

config/packages/twig.yaml, templates/admin/layout.html.twig
This PR adds a version string in the footer of the admin pages. The updater scripts automatically set a value to the environment variable INSTALLED_VERSION. This commit leverages that value, by passing it on to Twig and than letting outputting it to all admin pages.
=> Version indications in the admin

assets/style/admin.scss, assets/style/components/_activity.scss, assets/style/main.scss, src/Controller/Admin/AdminController.php, src/Tests/AuthWebTestCase.php, templates/admin/index.html.twig, tests/Functional/Controller/Admin/ActivityControllerTest.php, tests/Functional/Controller/Admin/AdminControllerTest.php, tests/Functional/Controller/Admin/RegistrationControllerTest.php
This PR updates the styling of the admin overview page. It now shows the upcoming/in progress activities, as these are likely to be the most relevant. It borrows from the old styling of the organise module.
=> Update styling of the admin overview page

public/update.php
This commit fixes a bug where the updater tried to load the environment variables from an invalid path. This was due to a code copy mistake when transitioning to Symfony 5.
=> Updater invalid path bugfix

src/Form/Activity/ActivityEditType.php
Previously, the author field was hidden when the user was only member of a single active group. However, that group was not persisted with the newly created activity, which causes the person that created the activity to be unable to view or edit it; only admins can see it. This PR simplifies the flow by always showing the selection box. The browser automatically sets a default option.
=> Always show an author selection

config/packages/security.yaml
With the upgrade to PHP8 and the changes to the OpenID Connect setup, the "Remember Me" functionality was inadvertently disabled for OIDC logins. This PR intends to rectify that change.
=> OpenID Connect remember me

templates/activity/show.html.twig
This PR removes the reserve list names from the frontend. The functionality serves no practical purpose and can therefore be removed.
=> Remove reserve list names from frontend

src/Entity/Security/LocalAccount.php, src/Form/Security/Import/ImportAccountsFlow.php, src/Form/Security/Import/ImportedAccounts.php, src/Form/Security/Import/UploadCsvType.php, tests/Functional/Controller/Admin/SecurityControllerTest.php
fixed the non existent error handing for the account import, and added a check to make sure it doesn't contain any duplicate email or oidc fields.
=> chore: add error handling to account import

composer.json, composer.lock, public/revert.php, public/update.php
This PR fixes the updater and revert scripts, with a couple of changes.
1. The last step of the updating process doesn't `yield` anymore, since apparently that doesn't trigger the `return` statement, resulting in an endless loop.
2. Database dumps are now stored as gzip files; the mysql-dump package currently contains a bug when loading uncompressed dumps, and this decreases the size of a backup as well. This means that the zlib extension is required now as well.
3. After restoring a dump, the `enable-maintenance.txt` is removed, re-enabling the kiwi installation automatically.
4. The confirmation button after a revert now actually works.
Lastly, duplicate code has been removed, simplifying the reverter script enormously.
=> Updater fixes
