- INSTALL.md
- README.md
- composer.json
- composer.lock
- public/.htaccess
- src/Entity/Group/Taxonomy.php
- src/Kernel.php
- symfony.lock
Additional documentation, as well as a couple of small fixes necessary for deploying to a production server.
> Fixes and documentation for running kiwi in a production environment

- composer.lock
- symfony.lock
> Forgot the lock files.

- .github/workflows/main.yml
> Fix php version

- src/Controller/Admin/ActivityController.php
- src/Controller/Organise/ActivityController.php
fixed the issue were prices would not change if there was a registration with a deleted date
> Price change fixed

- src/Controller/Organise/RegistrationController.php
Issue#152 - Fixed Issue where the site would give a 405 when an Organiser tried to deregister a user.
> Issue #152 - 405 on deregistering person from activity through Organise

- composer.json
- composer.lock
- config/bundles.php
- config/packages/test/dama_doctrine_test_bundle.yaml
- phpunit.xml.dist
- src/DataFixtures/Activity/ActivityFixture.php
- src/DataFixtures/Location/LocationFixture.php
- symfony.lock
- tests/Helper/TestData.php
The intent of this pull request is to ease the writing of unit tests for all different kinds of test data. A TestData class is added, and a proof of concept is shown.
> Generated test data permutations

- .github/workflows/main.yml
This release fixes the PHP version to be compatible with 7.4.0
> Set minimum PHP version to 7.4.0

- public/update.php
This change fixes the usage of the mysqldump utility.
> Load the MySQLDump utility when running it

- INSTALL.md
changed the way users are created, old commands where outdated
> small change in INSTALL.MD

- templates/organise/activity/amountpresent.html.twig
- templates/organise/activity/presentcount.html.twig
Bug fixed where on the organiser page within the setCountPresent form the back button would take you back to admin page
> Bug fixed with organiser page

- src/Entity/Activity/Activity.php
- src/Form/Activity/Admin/ActivityEditType.php
Added more help and added validation for start/end date.
> More validation

- src/Form/Activity/Admin/ActivityEditType.php
> Fix: ActivityEditType capacity can be 0

- assets/style/components/admin/_form.scss
- src/Form/Activity/Admin/ActivityEditType.php
- src/Form/Activity/Admin/ActivityNewType.php
- templates/admin/activity/edit.html.twig
- templates/admin/activity/new.html.twig
Fixed #158 
Added * next to required fields and
added message informing user about this
> Fix: Activity required fields are marked

- src/Controller/Admin/GroupController.php
- src/Controller/Security/LoginController.php
- src/Controller/Security/PasswordController.php
- src/Mail/MailService.php
- src/Tests/Database/Mail/MailFixture.php
- tests/Functional/Command/CreateLocalAccountCommandTest.php
- tests/Functional/Controller/Admin/GroupControllerTest.php
- tests/Functional/Controller/Admin/MailControllerTest.php
- tests/Functional/Controller/Admin/RegistrationControllerTest.php
- tests/Functional/Controller/Security/LoginControllerTest.php
- tests/Functional/Controller/Security/PasswordControllerTest.php
Just opening a draft to see how sonarcloud feels about it.
- Group
- Mail
- Password
- Login
- CreateLocalAccount
> PR for coverage

- src/Form/Activity/PresentType.php
PresentType.php (form) -> changed the ChoiceType class to include expended => true, multiple => false
This should make it easier for admins to set present
> Modified the way Present Types are set to be more usefull.

- tests/Integration/Form/Activity/ActivityEditTypeTest.php
Wrote testBuildForm() function in ActivityEditTypeTest file
> Test: ActivityEditTypeTest

- templates/activity/show.html.twig
This PR adds the name of the group that's the author of an activity in the frontend.
> Show the (organising) author group name on activities

- composer.lock
- phpstan-baseline.neon
- src/Form/Security/LocalAccountType.php
- src/Repository/RegistrationRepository.php
- symfony.lock
- tests/Unit/EventSubscriber/MailNotificationSubscriberTest.php
- yarn.lock
This branch is to bring develop up to date with all packages that are able to be updated since the switch to php 8 and symfony 5.4.
It also fixes some lint errors that were still left within the development branch. 
Lastly it fixes failed test that somehow got broken by all these updates.
> Development dependencies, lint and test fixes.

- templates/admin/activity/show.html.twig
- templates/admin/group/show.html.twig
- templates/admin/mail/show.html.twig
- templates/admin/security/show.html.twig
- templates/components/tab.html.twig
This PR adds an overview of all the activities a user account has been registered to, as well as an overview of all the groups that an account has been linked with. This information has been added to the user admin page. To accomplish this, the tabbing functionality in the admin has been extracted to a component. All existing tabs have been refactored to utilize this code.
> Groups and registrations in account overview

- migrations/Version20221202230206.php
- src/Log/EventService.php
A fix for the DB. The issue was raised here: https://github.com/jasperweyne/helpless-kiwi/issues/352
> Migration kiwi relation foreign key fix

- fixtures/Activity.yaml
- migrations/Version20221117214306.php
- migrations/Version20230328225759.php
- src/Controller/Admin/ActivityController.php
- src/Controller/Admin/AdminController.php
- src/Entity/Activity/Activity.php
- src/Entity/Activity/PriceOption.php
- src/Entity/Activity/Registration.php
- src/Repository/ActivityRepository.php
- src/Repository/GroupRepository.php
- src/Template/Attribute/MenuItem.php
- src/Template/Attribute/SubmenuItem.php
- src/Tests/Database/Activity/ActivityFixture.php
- templates/admin/activity/activate.html.twig
- templates/admin/activity/archive.html.twig
- templates/admin/activity/index.html.twig
- templates/admin/activity/show.html.twig
- templates/admin/layout.html.twig
- tests/Functional/Controller/Admin/ActivityControllerTest.php
- tests/Unit/Entity/Activity/ActivityTest.php
- tests/Unit/Repository/ActivityRepositoryTest.php
PR Draft to see if I can finally satisfy the database tests
> feat: activity archive

- src/Controller/Admin/SecurityController.php
- src/Form/Security/LocalAccountType.php
- templates/admin/security/show.html.twig
- tests/Functional/Controller/Admin/SecurityControllerTest.php
- tests/Integration/Form/Security/LocalAccountTypeTest.php
Very small PR, I noticed it wasn't possible to edit local accounts.
> fix: editing of LocalAccount

- src/Repository/ActivityRepository.php
Hotfix for the issue @jasperweyne mentioned in [the discord](https://discord.com/channels/838843751509393458/838843751509393462/1115622426768855083).
> fix(ActivityRepo): Sort activity and archive descending

- src/Form/Security/LocalAccountType.php
- tests/Integration/Form/Security/LocalAccountTypeTest.php
Create account now require given and family name.
Added a check that there is no existing account with the same email.
> feat: resolve #396

- templates/admin/layout.html.twig
> Order search results based on match quality

- public/revert.php
- public/update.php
Completely restructure the code of update.php to be clearer and more consise, while also improving stability of the update process and removing the automated revert process from this script
> Overhaul of the updater
